/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Camada_cigueñas(props) {
  const { nodes, materials } = useGLTF("./static/camadagansos.glb");
  return (
    <group {...props} dispose={null} scale={0.1} position={[0,40,0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ganso.geometry}
        material={materials.Material__2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ganso001.geometry}
        material={materials["Material__2.001"]}
        position={[-159.924, 0, -60.269]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ganso002.geometry}
        material={materials["Material__2.002"]}
        position={[136.152, 0, -60.269]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ganso003.geometry}
        material={materials["Material__2.003"]}
        position={[-300.743, 0, -167.953]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ganso004.geometry}
        material={materials["Material__2.004"]}
        position={[294.3, 0, -167.953]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("./static/camadagansos.glb");




